// Code generated by goctl. DO NOT EDIT.
// Source: authentication.proto

package server

import (
	"context"

	"go-rpc-todo-list_/app/rpc/authentication/internal/logic"
	"go-rpc-todo-list_/app/rpc/authentication/internal/svc"
	"go-rpc-todo-list_/app/rpc/authentication/types/authentication"
)

type AuthRPCServer struct {
	svcCtx *svc.ServiceContext
	authentication.UnimplementedAuthRPCServer
}

func NewAuthRPCServer(svcCtx *svc.ServiceContext) *AuthRPCServer {
	return &AuthRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthRPCServer) Authentication(ctx context.Context, in *authentication.AuthenticationReq) (*authentication.AuthenticationResp, error) {
	l := logic.NewAuthenticationLogic(ctx, s.svcCtx)
	return l.Authentication(in)
}
