// Code generated by goctl. DO NOT EDIT.
package types

type ReqigsterReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type UserInfoResp struct {
	Id       uint   `json:"id"`
	UserName string `json:"user_name"`
}
