// Code generated by goctl. DO NOT EDIT.
// Source: task.proto

package server

import (
	"context"

	"go-rpc-todo-list_/app/rpc/task/internal/logic"
	"go-rpc-todo-list_/app/rpc/task/internal/svc"
	"go-rpc-todo-list_/app/rpc/task/types/task"
)

type TaskRPCServer struct {
	svcCtx *svc.ServiceContext
	task.UnimplementedTaskRPCServer
}

func NewTaskRPCServer(svcCtx *svc.ServiceContext) *TaskRPCServer {
	return &TaskRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskRPCServer) CreateTask(ctx context.Context, in *task.CreateTaskReq) (*task.CreateTaskResp, error) {
	l := logic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}

func (s *TaskRPCServer) GetTaskInfo(ctx context.Context, in *task.TaskInfoReq) (*task.TaskInfoResp, error) {
	l := logic.NewGetTaskInfoLogic(ctx, s.svcCtx)
	return l.GetTaskInfo(in)
}
