// Code generated by goctl. DO NOT EDIT.
package types

type CreateTaskReq struct {
	TaskName string `json:"task_name"`
}

type CreateTaskResp struct {
	TaskId string `json:"task_id"`
}

type GetTaskInfoReq struct {
	TaskId string `path:"task_id"`
}

type GetTaskInfoResp struct {
	TaskInfo
}

type TaskInfo struct {
	TaskId   string `path:"task_id"`
	TaskName string `json:"task_name"`
}
