// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	authentication "go-rpc-todo-list_/app/api/auth-api/internal/handler/authentication"
	"go-rpc-todo-list_/app/api/auth-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: authentication.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
